version: "3"

services:
  some-postgres:
    container_name: some-postgres
    image: postgres:16.0-bookworm
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=example-user
      - POSTGRES_PASSWORD=prueba123*

  some-mariadb:
    container_name: some-mariadb
    image: mariadb:11.1.2-jammy
    ports:
      - "3306:3306"
    volumes:
      - mariadb-volume:/var/lib/mysql
    environment:
      - MARIADB_USER=example-user
      - MARIADB_PASSWORD=prueba123*
      - MARIADB_ROOT_PASSWORD=prueba123*
      - MARIADB_DATABASE=mariadb

  cloudbeaver:
    container_name: cloudbeaver
    depends_on:
      - some-postgres
      - some-mariadb
    image: dbeaver/cloudbeaver:latest
    ports:
      - "8080:8978"
    volumes:
      - cloudbeaver-volume:/opt/cloudbeaver/workspace

volumes:
  postgres-volume:
    name: "postgres-volume"
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .\.local_data\postgres
  mariadb-volume:
    name: "mariadb-volume"
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .\.local_data\mariadb
  cloudbeaver-volume:
    name: "cloudbeaver-volume"
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .\.local_data\cloudbeaver

  # opción 1 volumen en sección de services
  # services:
  #   some-database:
  #     volumes:
  #       - .\data\some-database:/var/lib/some-database/data

  # opción 2 volumen en sección de volúmenes
  # services:
  #   some-database:
  # volumes:
  #   some-database-volume:/var/lib/some-database/data
  # volumes:
  #   some-database-volume:
  #     name: "some-database-volume"
  #     driver: local
  #     driver_opts:
  #       o: bind
  #       type: none
  #       device: .\data\some-database

  # opción 3 volumen externo
  # services:
  #   some-database:
  #     volumes:
  #       - some-database-volume:/var/lib/some-database/data
  # volumes:
  #   some-database-volume:
  #     external: true
